// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1TlhEfKqvub6WauDpslcrGy3goVkJDms',
    appId: '1:833820429264:web:f54a98730cb22b98ff47d5',
    messagingSenderId: '833820429264',
    projectId: 'halalmaps-c7560',
    authDomain: 'halalmaps-c7560.firebaseapp.com',
    storageBucket: 'halalmaps-c7560.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7mivtP4Nd8NvENK6ZuEoRe9iZe4WP42Y',
    appId: '1:833820429264:android:ded8dd1cc68b5d84ff47d5',
    messagingSenderId: '833820429264',
    projectId: 'halalmaps-c7560',
    storageBucket: 'halalmaps-c7560.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuxlbao2RirWLHEyFPzDD5ac793JZyiiE',
    appId: '1:833820429264:ios:04b7b93c1e47dc6eff47d5',
    messagingSenderId: '833820429264',
    projectId: 'halalmaps-c7560',
    storageBucket: 'halalmaps-c7560.appspot.com',
    iosClientId: '833820429264-gggk858srkg2195q1chnagbhbutq4vdi.apps.googleusercontent.com',
    iosBundleId: 'com.example.halalapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuxlbao2RirWLHEyFPzDD5ac793JZyiiE',
    appId: '1:833820429264:ios:04b7b93c1e47dc6eff47d5',
    messagingSenderId: '833820429264',
    projectId: 'halalmaps-c7560',
    storageBucket: 'halalmaps-c7560.appspot.com',
    iosClientId: '833820429264-gggk858srkg2195q1chnagbhbutq4vdi.apps.googleusercontent.com',
    iosBundleId: 'com.example.halalapp',
  );
}
